### ISSUE TITLE
Why is a branch in an open PR deployed to live? 

### ISSUE THREAD

**Issue by pgleeson** [combine-org/combine-org.github.io#102]
This PR adding the attendee list is currently still open: https://github.com/combine-org/combine-org.github.io/pull/101

However the attendee list is live at: https://combine-org.github.io/events/, and the changes are not on master... Only changes approved and merged should be deployed. Any idea @Fontanapink?

**Comment by cjmyers** [comment]
Very strange indeed.  It seems it is deploying the branch rather than master.

**Comment by nickerso** [comment]
seems the latest PR built by the CI will go straight onto production (so my date change PR just replaced #101 so the attendees list is not live now).

@pgleeson I suspect if we bring #101 up to date it will rebuild and go back onto production...which might be a good thing?

**Comment by cjmyers** [comment]
Interesting.  @Fontanapink any ideas how to make sure it is only deploying the master branch?

**Comment by pgleeson** [comment]
I see @Fontanapink has made some changes to the GHA config files. Let's see if PR #104 deploys or waits for a merge...

**Comment by pgleeson** [comment]
Looks like it's all running smoothly now with a deploy only going ahead after merge to master. Thanks @Fontanapink.

**Comment by Fontanapink** [comment]
Sorry about that, looks like there was a deploy github action on PRs.
Removed it!
