### ISSUE TITLE
Website migration steps

### ISSUE THREAD

**Issue by pgleeson** [combine-org/combine-org.github.io#105]
- [x] Create a test subdomain URL in an existing domain (e.g. co.mydomain.org) pointing to 131.215.225.44 (IP of co.mbine.org) and make sure it renders properly (note, currently http://131.215.225.44/ points to a page with Harmony 2019)
- [x] Fix any issues with setup in Caltech
- [x] Transfer domain. 
- [x] Create co.mbine.org on Namecheap and point to correct IP
- [x] Create **old_co**.mbine.org on Namecheap and point to https://combine-org.github.io/OldWebsite/ (hosted at https://github.com/combine-org/OldWebsite)
- [x] Update https://github.com/combine-org/OldWebsite to ensure as much content present there as possible
- [x] Move co.mbine.org to point to https://combine-org.github.io/
- [ ] Add info on new website about accessing old content
- [ ] Shut down old site at CalTech
- [ ] Update contact email address for the site (current listed as `biomodels-net-support@lists.sf.net`) in the admin interface at http://co.mbine.org/admin/settings/site-information

**Comment by cjmyers** [comment]
Once transferred, need to setup the following records:
A @ 131.215.225.44
A co 131.215.225.44
A www.co 131.215.225.44

**Comment by pgleeson** [comment]
Update on this is that we're waiting for Andreas Dräger to return to the office (mid Sept) to commence transfer of the domain

**Comment by cjmyers** [comment]
Done

Still need to decide how this is covered recurring

@pgleeson you can finish moving the old material.  Please modify host records or tell me what needs to be done to finish that.

**Comment by cjmyers** [comment]
Since the old site appears dead now, I've moved the domain to point to the new site.  @pgleeson please advise how you want things directed to the scrapped pages.

**Comment by pgleeson** [comment]
So at the moment http://www.co.mbine.org/OldWebsite/ contains the old homepage, but the links are broken, e.g. the Events link goes to http://www.co.mbine.org/events/.

The best option is to do for old_co.mbine.org (i.e. the **old_co** subdomain) what you did for the co subdomain on Namecheap, but point to the repo here: https://github.com/combine-org/OldWebsite. Then http://old_co.mbine.org/events etc should work. 

While many of the old pages are committed in that repo, not all are, and it would be easiest to scrape the rest from a live server, but they should be retrievable from the zip files Nico created.

**Comment by cjmyers** [comment]
I'm not sure how to setup old_co.  I tried to create a CNAME record in namecheap, but it will not let me create one for www.co.mbine.org/OldWebsite/.  Do you know what needs to be setup there?  You should have the login information, if you want to try to set it up.

**Comment by pgleeson** [comment]
@cjmyers Ok, will try. Could you send me the login info again in a slack direct message?

**Comment by cjmyers** [comment]
Done

**Comment by pgleeson** [comment]
Migrated to http://old_co.mbine.org.

Problems on that site can be reported at https://github.com/combine-org/OldWebsite/issues.
