### ISSUE TITLE
Change `Event`'s layout to match that of a `current event`

### ISSUE THREAD

**Issue by Fontanapink** [combine-org/combine-org.github.io#135]
So currently, "Current Event" and "Past"/"Future" events are displayed differently. So we need to change the layout of all of them to look alike. This should solve the following issue:

"Thanks @Fontanapink - this looks great. Just a quick question... if we use [co.mbine.org/author/combine-2023](https://co.mbine.org/author/combine-2023/) as a URL to start promoting and linking to the meeting, will it be possible to automatically redirect that page to [co.mbine.org/events](https://co.mbine.org/events/) once it becomes the current event? Just wondering as currently the page [co.mbine.org/author/harmony-2023](https://co.mbine.org/author/harmony-2023/) is very different to [co.mbine.org/events](https://co.mbine.org/events/)"

**Comment by nickerso** [comment]
@Fontanapink - would it be possible to keep past events as they are (i.e., an archive) and just make the current and future events similar? Future events will be cycling through as [co.mbine.org/events](https://co.mbine.org/events/) whereas past events wouldn't make it back there.

**Comment by Fontanapink** [comment]
I will look into this. So past events as they are then? With minimal information

**Comment by nickerso** [comment]
I think so, we should be editing the descriptions of past events to summarise them and make sure any content that needs to persist is sorted out.

**Comment by nickerso** [comment]
yeah, thats the kind of content that would need to persist. But links to registration pages, breakout submissions, etc. won't be.

**Comment by Fontanapink** [comment]
the PR #136 solved this
