### ISSUE TITLE
Add Past Events

### ISSUE THREAD

**Issue by cjmyers** [combine-org/combine-org.github.io#42]
An important activity of COMBINE is to organise common meetings, where the developers of the different standards can meet and work together. In 2010, we inaugurated a new, broader series of meetings to replace, the existing individual forums and hackathons. The new meetings are a recognition of the fact that there are multiple allied standardization efforts that should work together towards smooth interoperability. Moreover, we believe a joint meeting makes good economic sense: compared to multiple separate workshops, they reduce the overall number of meetings, travel, and money spent over the year.

Those events, as others related to our field of research are gathered in a calendar.

Annual COMBINE forums
The annual COMBINE forums are workshop-style events with oral presentations plus discussion, poster and breakout sessions. They are aimed at further developing the standards. The meetings cover the COMBINE standards and associated or related standardization efforts. The participants are everyone wishing to participate to the development of the standards.
- [ ] COMBINE 2020 The 11th annual COMBINE forum will be an online (virtual) meeting from 5 to 9 October 2020.
- [ ] COMBINE 2019 The tenth annual COMBINE forum was organized by Martin Golebiewski, Wolfgang Müller and Dagmar Waltemath at HITS in Heidelberg (Germany) from 15 to 19 July 2019.
- [ ] COMBINE 2018 The ninth annual COMBINE forum was organized by Curtis Madsen and Nicholas Roehner in Boston, MA (USA) from 8 to 12 October 2018.
- [ ] COMBINE 2017 The eighth annual COMBINE forum was organized by Marco Antoniotti in Milan (Italy) from 9 to 13 October 2017.
- [ ] COMBINE 2016 The seventh annual COMBINE forum was organized by the group of Anil Wipat in Newcastle upon Tyne (UK) from 19 to 23 September 2016.
- [ ] COMBINE 2015 The sixth annual COMBINE forum was organized by the group of Chris Myers at the University of Utah in Salt Lake City, UT USA from 12 to 16 October 2015.
- [ ] COMBINE 2014 The fifth annual COMBINE forum was organized by the University of Southern California, in L.A., USA, from 18 to 22 August 2014.
- [ ] COMBINE 2013 The fourth annual COMBINE forum was organized by the bioinformatics unit of Curie Institute, in Paris, FR, from 16 to 20 September 2013.
- [ ] COMBINE 2012 The third annual COMBINE forum was organized by the group of Gary Bader, in Toronto, CA, from 15 to 19 August 2012, as a satellite of the 13th ICSB.
- [ ] COMBINE 2011 The second annual COMBINE forum was organized by Martin Golebiewski at HITS in Heidelberg, DE, from 3 to 7 September 2011, as a satellite of the 12th ICSB.
- [ ] COMBINE 2010 The first annual COMBINE meeting was organized by the group of Igor Goryanin, in Edinburgh, UK from 6 to 9 October. It was a joint event with the 10th SBML anniversary, as a satellite of the 11th ICSB

HARMONY hackathons

The Hackathons on Resources for Modeling in Biology (HARMONY) are a series of Hackathon-type meetings, with a focus on development of the support for standards, their interoperability and software infrastructure. Focus is not on general discussions or oral presentations but hands-on hacking and interaction between people focused on practical development of standards and supporting software. The participants are generally developers.

- [ ] HARMONY 2021 is being organized as a virtual meeting, March 22 – 26, 2021.
- [ ] HARMONY 2020 was organized by Henning Hermjakob at EMBL-EBI (Cambridge, UK), March 9 – 13, 2020.
- [ ] HARMONY 2019 was hosted by Mike Hucka at Caltech in Pasadena, California (USA) from 25 to 29 March 2019.
- [ ] HARMONY 2018 was hosted by the Department of Computer Science at the University of Oxford, UK, from 18 to 22 June 2018.
- [ ] HARMONY 2017 was hosted by the group of Herbert Sauro in Seattle, USA, from 26 to 30 June 2017.
- [ ] HARMONY 2016 was hosted by the Auckland Bioengineering Institute in Auckland, New Zealand, from 7 to 11 June 2016.
- [ ] HARMONY 2015 was organized by the groups of Falk Schreiber and Dagmar Waltemath in Wittenberg, Germany, from 20 to 24 April 2015.
- [ ] HARMONY 2014 was organized by the Manchester Institute of Biotechnology, UK, from 22 to 25 April 2014.
- [ ] HARMONY 2013 was organized by the Virtual Cell group, University of Connecticut Health Center, USA, from 20 to 23 May 2013.
- [ ] HARMONY 2012 was organized by the group of Chris Evelo in Maastricht, NL, from 21 to 25 May 2012
- [ ] HARMONY 2011 was organized by the group of Chris Sander in New York City, USA, from 18 to 22 April 2011.

Prior to the HARMONY hackathons, joint meetings had been organised in an ad-hoc manner.

- [ ] SBML BioModels.net hackathon, 1 to 4 May 2010, Cambridge, UK
- [ ] combined CellML SBGN SBO BioPAX MIASE, 5 to 9 April 2009, Waiheke, NZ
- [ ] Super-hackathon "standards and ontologies for Systems Biology", 28 January to 2 February 2008, Okinawa, JP

**Comment by nickerso** [comment]
Superseded by the new link to the "old" site from the main events page?

**Comment by Fontanapink** [comment]
@cjmyers I think we can close this one

**Comment by cjmyers** [comment]
Agreed
