### ISSUE TITLE
Add how to organize an event

### ISSUE THREAD

**Issue by cjmyers** [combine-org/combine-org.github.io#44]
Organizing a COMBINE event

The coordination of COMBINE owes much to the people organizing the meetings, and in particular the hosts of the events. Conversely, COMBINE events have become such successes that hosting them boosts recognition in the field, and permits to build or to strengthen collaborations.

People interested in organizing a meeting should start by filling the interest survey. This will permit to highlight the advantages and potential issues associated with each application, and start the discussion with COMBINE coordinators. More information about the organization of COMBINE meetings can be found in the detailed guidelines.

**Comment by pgleeson** [comment]
Fixed in #53
