### ISSUE TITLE
Link broken for Abstracts on COMBINE21 page

### ISSUE THREAD

**Issue by pgleeson** [combine-org/combine-org.github.io#49]
On https://combine-org.github.io/events/ link for abstract submission goes to a submission confirmation page. 

@chofski are there short urls now for these?

**Comment by chofski** [comment]
I think that is because the form is closed. Not familiar with Google forms so no idea.

I havn't generated the short URLs as not needed for the website, but feel free to create some (although no idea why they are needed now).

**Comment by pgleeson** [comment]
Ok, I've changed that now on the Abstracts form. It was set as closed on the "Responses" tab.

Re short urls, it was just for the registration announcement mail, but a hyperlink can be put in instead.
