### ISSUE TITLE
Add overview image to homepage?

### ISSUE THREAD

**Issue by pgleeson** [combine-org/combine-org.github.io#57]
Would it be useful to add this to to the meeting homepage, or is it too much info?
Is it even still up to date?

<img width="673" alt="Screenshot 2021-10-04 at 18 15 28" src="https://user-images.githubusercontent.com/1556687/135895199-a31ecf6c-b6c9-4169-8a88-4106d3646058.png">

**Comment by cjmyers** [comment]
I think this is too much.  Sched already handles time zones and has a grid view.

**Comment by pgleeson** [comment]
Ok.
