### ISSUE TITLE
Add link to HARMONY 2022 calendar

### ISSUE THREAD

**Issue by nickerso** [combine-org/combine-org.github.io#84]
This calendar will only be accessible to registrants of HARMONY 2022: https://calendar.google.com/calendar/u/0?cid=bW1wbnNwMzVoYWplMnZjNjJuYjdoMWRmdG9AZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ

**Comment by Fontanapink** [comment]
Question @nickerso: you want this link published in the website? Anyone who clicks it will be able to add the schedule to their calendar

**Comment by nickerso** [comment]
Thanks @Fontanapink - and yes, only people added to the calendar will be able to add it. Would be good to have text similar to the following just to make it clear..

Please see this [Google Calendar](https://calendar.google.com/calendar/u/0?cid=bW1wbnNwMzVoYWplMnZjNjJuYjdoMWRmdG9AZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ) for the live HARMONY 2022 Schedule. This calendar is only accessible to registered attendees. If you have difficulties accessing the calendar please contact the organisers.

**Comment by nickerso** [comment]
Sorry, perhaps better to use this link: https://calendar.google.com/calendar/u/0/embed?src=mmpnsp35haje2vc62nb7h1dfto@group.calendar.google.com - as that gives the web view of the calendar rather than the direct add to calendar option.

**Comment by nickerso** [comment]
thanks @Fontanapink !
