### ISSUE TITLE
Abstract submission for COMBINE 2022

### ISSUE THREAD

**Issue by nickerso** [combine-org/combine-org.github.io#92]
For abstract submission we need this information on the website:

To submit an abstract for the COMBINE forum on Saturday October 8, please use the official ICSB abstract submission portal on EasyChair: 
- Submit your abstract at https://easychair.org/conferences/?conf=icsb2022
- Select "**COMBINE: Satellite Event**" as your submission topic

**Comment by Fontanapink** [comment]
I've added this information in the main body of the event. Does this work?

**Comment by cjmyers** [comment]
Have you pushed?  I don't see it on the page.  Also, please add the dates:

Breakouts/Tutorials and Talk Submission Due Dates August 26, 2022
Acceptance September 9, 2022

You can remove COMBINE Forum date, since it is already shown a bit higher up on the left.

**Comment by Fontanapink** [comment]
Now yes

**Comment by nickerso** [comment]
looks good, thanks!
